//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.10 at 01:47:19 PM IST 
//


package com.dw.automation.support;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for userProfile element declaration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;element name="userProfile">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;sequence>
 *           &lt;element name="bonus_points" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *           &lt;element name="cac" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *           &lt;element name="email" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *           &lt;element name="inUse" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *           &lt;element name="isParent" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *           &lt;element name="isTeacher" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *           &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *           &lt;element name="parent_cc_type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *           &lt;element name="parent_no_child" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *           &lt;element name="password" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *           &lt;element name="profile_key" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *           &lt;element name="teacher_cc_type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;/sequence>
 *         &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}short" />
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "bonusPoints",
    "cac",
    "email",
    "inUse",
    "isParent",
    "isTeacher",
    "name",
    "parentCcType",
    "parentNoChild",
    "password",
    "profileKey",
    "teacherCcType"
})
@XmlRootElement(name = "userProfile")
public class UserProfile {

    @XmlElement(name = "bonus_points")
    protected byte bonusPoints;
    @XmlElement(required = true)
    protected String cac;
    @XmlElement(required = true)
    protected String email;
    @XmlElement(required = true)
    protected String inUse;
    @XmlElement(required = true)
    protected String isParent;
    @XmlElement(required = true)
    protected String isTeacher;
    @XmlElement(required = true)
    protected String name;
    @XmlElement(name = "parent_cc_type", required = true)
    protected String parentCcType;
    @XmlElement(name = "parent_no_child", required = true)
    protected String parentNoChild;
    @XmlElement(required = true)
    protected String password;
    @XmlElement(name = "profile_key", required = true)
    protected String profileKey;
    @XmlElement(name = "teacher_cc_type", required = true)
    protected String teacherCcType;
    @XmlAttribute
    protected Short id;

    /**
     * Gets the value of the bonusPoints property.
     * 
     */
    public byte getBonusPoints() {
        return bonusPoints;
    }

    /**
     * Sets the value of the bonusPoints property.
     * 
     */
    public void setBonusPoints(byte value) {
        this.bonusPoints = value;
    }

    /**
     * Gets the value of the cac property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCac() {
        return cac;
    }

    /**
     * Sets the value of the cac property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCac(String value) {
        this.cac = value;
    }

    /**
     * Gets the value of the email property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmail() {
        return email;
    }

    /**
     * Sets the value of the email property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmail(String value) {
        this.email = value;
    }

    /**
     * Gets the value of the inUse property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInUse() {
        return inUse;
    }

    /**
     * Sets the value of the inUse property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInUse(String value) {
        this.inUse = value;
    }

    /**
     * Gets the value of the isParent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsParent() {
        return isParent;
    }

    /**
     * Sets the value of the isParent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsParent(String value) {
        this.isParent = value;
    }

    /**
     * Gets the value of the isTeacher property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsTeacher() {
        return isTeacher;
    }

    /**
     * Sets the value of the isTeacher property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsTeacher(String value) {
        this.isTeacher = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the parentCcType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParentCcType() {
        return parentCcType;
    }

    /**
     * Sets the value of the parentCcType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParentCcType(String value) {
        this.parentCcType = value;
    }

    /**
     * Gets the value of the parentNoChild property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParentNoChild() {
        return parentNoChild;
    }

    /**
     * Sets the value of the parentNoChild property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParentNoChild(String value) {
        this.parentNoChild = value;
    }

    /**
     * Gets the value of the password property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPassword() {
        return password;
    }

    /**
     * Sets the value of the password property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPassword(String value) {
        this.password = value;
    }

    /**
     * Gets the value of the profileKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProfileKey() {
        return profileKey;
    }

    /**
     * Sets the value of the profileKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProfileKey(String value) {
        this.profileKey = value;
    }

    /**
     * Gets the value of the teacherCcType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTeacherCcType() {
        return teacherCcType;
    }

    /**
     * Sets the value of the teacherCcType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTeacherCcType(String value) {
        this.teacherCcType = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setId(Short value) {
        this.id = value;
    }

}
